all:
	clang++ -std=c++11 -DZION_TEST -I/home/paul/github/Zion test.cpp

pp:
	clang++ -std=c++11 -E -C -fmacro-backtrace-limit=0 -DZION_TEST -I/home/paul/github/Zion function/adaptor.h
    
clean:
	rm a.out


